---
- name: Set Zookeeper
  unarchive:
    src:  zookeeper-3.4.11.tar.gz
    dest: /opt

- name: Set Zookeeper Link
  file:
    src:  /opt/zookeeper-3.4.11
    dest: /opt/zookeeper
    state:  link

- name: Set Zookeeper Config
  copy:
    src:  zoo.cfg
    dest: /opt/zookeeper/conf/zoo.cfg
