---
- name: install openjdk
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "java-1.8.0-openjdk"
    - "java-1.8.0-openjdk-headless"
    - "java-1.8.0-openjdk-devel"

- name: correct java version selected
  alternatives:
    name: java
    path: "/usr/lib/jvm/java-1.8.0-openjdk/bin/java"
    link: /usr/bin/java
